// redirects.mjs - dist/_redirects (Netlify-style) and dist/.htaccess (Apache) from restructure.json `redirects`
// (PIPELINE role). One 301 per moved page, straight to its final path, matching both served forms (/old and /old/),
// so no moved URL takes two hops (docs/SITE-ARCHITECTURE.md section 8). Fails closed on a chain, a target that is not
// a page, a rule that would shadow a live page, a target that disagrees with remap(), or a missing match form.
import { ownPath, servedPath } from './util.mjs';

const reEsc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

export function buildRedirects(restructure, { pagePaths, remapOwn }) {
  const errors = [];
  const pages = new Set(pagePaths);
  const rules = [];
  const froms = new Set(restructure.redirects.map((r) => r.from));
  for (const r of restructure.redirects) {
    const from = ownPath(r.from);
    const to = servedPath(ownPath(r.to));
    if (r.status !== 301) errors.push('redirect ' + from + ': status ' + r.status + ' (expected 301)');
    if (servedPath(remapOwn(from)) !== to) errors.push('redirect ' + from + ' -> ' + to + ' disagrees with remap() -> ' + servedPath(remapOwn(from)));
    if (!pages.has(to)) errors.push('redirect target is not a page: ' + to);
    if (froms.has(ownPath(r.to))) errors.push('redirect chain: ' + to + ' is itself redirected');
    if (pages.has(servedPath(from))) errors.push('redirect would shadow a live page: ' + servedPath(from));
    const want = ['/' + from, '/' + from + '/'];
    for (const w of want) if (!(r.match || []).includes(w)) errors.push('redirect ' + from + ': match[] lacks ' + w);
    rules.push({ from, to, status: 301, match: want });
  }
  if (rules.length !== Object.keys(restructure.moves).length) errors.push('redirects ' + rules.length + ' != moves ' + Object.keys(restructure.moves).length);
  for (const k of Object.keys(restructure.moves)) if (!rules.some((x) => x.from === k)) errors.push('moved page without a redirect: ' + k);

  const netlify = ['# Generated by src/build.mjs from src/content/restructure.json: one 301 per moved page, both URL forms.']
    .concat(rules.flatMap((x) => x.match.map((m) => m + ' ' + x.to + ' 301'))).join('\n') + '\n';
  const htaccess = [
    '# Generated by src/build.mjs from src/content/restructure.json: one 301 per moved page, both URL forms',
    '# (/old and /old/ are matched exactly; RedirectMatch, not Redirect, which would also prefix-match deeper paths).',
    'ErrorDocument 404 /404.html',
    '<IfModule mod_alias.c>',
    ...rules.map((x) => 'RedirectMatch 301 ^/' + reEsc(x.from) + '/?$ ' + x.to),
    '</IfModule>',
  ].join('\n') + '\n';
  return { rules, netlify, htaccess, errors };
}
